# Generated by Django 5.0.4 on 2024-04-30 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre de la parada')),
                ('address', models.CharField(max_length=250, verbose_name='Dirección de la parada')),
                ('latitude', models.FloatField(verbose_name='Latitud')),
                ('longitude', models.FloatField(verbose_name='Longitud')),
            ],
            options={
                'verbose_name': 'Parada',
                'verbose_name_plural': 'Paradas',
                'ordering': ['name'],
            },
        ),
    ]
