# Generated by Django 5.0.4 on 2024-04-30 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name'], 'verbose_name': 'parada', 'verbose_name_plural': 'paradas'},
        ),
    ]
